### ISSUE TITLE
public下的静态资源访问不到404

### ISSUE THREAD

**Issue by PrinceH** [huang-yi/shadowfax#26]
public下的静态资源访问不到404

**Comment by huang-yi** [comment]
如果你要使用swoole来处理静态文件，需要添加以下两个配置到`shadowfax.yml`的`server`项：

```yaml
server:
  document_root: public
  enable_static_handler: true
```
